import Databases.EquationsDatabase;

import java.sql.SQLException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {

        try {
            EquationsDatabase database = new EquationsDatabase();
            database.insertEquation("3+3=5");
            database.insertEquation("3+3=7");

            System.out.println(database.getAllEquations());
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }

    }
}
