import Databases.EquationsDatabase;

import java.sql.SQLException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {

        try {
            EquationsDatabase database = new EquationsDatabase();


            System.out.println(database.getAllTimeStamps().toString());
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }

    }
}
