import Databases.FunctionsDatabase;
import Databases.HistoryDatabase;

import java.sql.SQLException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {

        try {
            HistoryDatabase database = new HistoryDatabase();
            FunctionsDatabase functionsDB = new FunctionsDatabase(database.getCon());

        database.insertEquation("3+3");
        functionsDB.insertFunction("3");
            System.out.println(database.getAllTimeStamps());
            System.out.println(functionsDB.getAllFunctions());
        } catch (SQLException e) {
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        }

    }
}
